/**Author:zx**/
#include "StdAfx.h"
#include "XMLWrapperLight.h"


BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperLight)
	REGISTER_CLASS(Light)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Name,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,LightPos,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,LightDir,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,LightType,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Visible,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,CastShadows,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperLight,ColorDiffuse,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,ColorSpecular,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,ColorAmbient,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,InnerAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,OuterAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,FallOff,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Range,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Constant,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Linear,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Quadric,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Power,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperLight,Rotation,VALUE)
END_IMPL_SERIALIZATION_CLASS

CXMLWrapperLight::CXMLWrapperLight(void)
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_FLOAT3(LightPos)
	INIT_ATTRIBUTE_FLOAT3(LightDir)
	INIT_ATTRIBUTE_LONG(LightType)
	INIT_ATTRIBUTE_BOOL_VALUE(Visible,true)
	INIT_ATTRIBUTE_BOOL_VALUE(CastShadows,false)
	INIT_ATTRIBUTE_COLOR(ColorDiffuse)
	INIT_ATTRIBUTE_COLOR(ColorSpecular)
	INIT_ATTRIBUTE_COLOR(ColorAmbient)
	INIT_ATTRIBUTE_FLOAT_VALUE(InnerAngle,0.5)
	INIT_ATTRIBUTE_FLOAT_VALUE(OuterAngle,1.0)
	INIT_ATTRIBUTE_FLOAT_VALUE(FallOff,1.5)
	INIT_ATTRIBUTE_FLOAT_VALUE(Range,500)
	INIT_ATTRIBUTE_FLOAT_VALUE(Constant,1)
	INIT_ATTRIBUTE_FLOAT_VALUE(Linear,0.0001)
	INIT_ATTRIBUTE_FLOAT_VALUE(Quadric,0.00001)
	INIT_ATTRIBUTE_FLOAT_VALUE(Power,1.0)
	INIT_ATTRIBUTE_QUATERNION(Rotation)
}


CXMLWrapperLight::~CXMLWrapperLight(void)
{
}
