
#include "StdAfx.h"
#include "XMLWrapperMovie.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperMovie)
REGISTER_CLASS(MovieCell)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,MovieName,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,Title,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,Path,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,AutoClose,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,DialogPosX,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,DialogPosY,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,DialogWidth,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,DialogHeight,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,TextureWidth,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,TextureHeight,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,OverlayWidth,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,OverlayHeight,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,Active,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,OverlayPosX,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperMovie,OverlayPosY,VALUE)
END_IMPL_SERIALIZATION_CLASS

CXMLWrapperMovie::CXMLWrapperMovie(void)
{
	INIT_ATTRIBUTE_STRING(MovieName)
	INIT_ATTRIBUTE_STRING(Title)
	INIT_ATTRIBUTE_STRING(Path)

	INIT_ATTRIBUTE_BOOL(AutoClose)

	INIT_ATTRIBUTE_LONG(DialogPosX)
	INIT_ATTRIBUTE_LONG(DialogPosY)
	INIT_ATTRIBUTE_LONG(DialogWidth)
	INIT_ATTRIBUTE_LONG(DialogHeight)

	INIT_ATTRIBUTE_LONG(TextureWidth)
	INIT_ATTRIBUTE_LONG(TextureHeight)
	INIT_ATTRIBUTE_LONG(OverlayWidth)
	INIT_ATTRIBUTE_LONG(OverlayHeight)

	INIT_ATTRIBUTE_FLOAT(OverlayPosX);
	INIT_ATTRIBUTE_FLOAT(OverlayPosY);

	INIT_ATTRIBUTE_BOOL(Active);
}

CXMLWrapperMovie::~CXMLWrapperMovie(void)
{
}
