#pragma once
#include "XMLSerialize.h"

class CXMLWrapperPart : public CXMLSerialize
{
public:
	CXMLWrapperPart(void);
	~CXMLWrapperPart(void);

	IMPL_ATTRIBUTE_STRING(Name)
	IMPL_ATTRIBUTE_STRING(FileName)
	IMPL_ATTRIBUTE_LONG(Type)
    IMPL_ATTRIBUTE_FLOAT(Length)
	IMPL_ATTRIBUTE_FLOAT3(FirstPointPos)
    IMPL_ATTRIBUTE_LONG(Orientation)
    IMPL_ATTRIBUTE_FLOAT(Mass)
    IMPL_ATTRIBUTE_FLOAT(EdgeStiff)
    IMPL_ATTRIBUTE_FLOAT(BendStiff)
    IMPL_ATTRIBUTE_FLOAT(TorsionStiff)
    IMPL_ATTRIBUTE_FLOAT(EdgeDamp)
    IMPL_ATTRIBUTE_FLOAT(ExtraEdgeDamp)
    IMPL_ATTRIBUTE_FLOAT(BendDamp)
    IMPL_ATTRIBUTE_FLOAT(TorsionDamp)
    IMPL_ATTRIBUTE_FLOAT(Interval)
    IMPL_ATTRIBUTE_FLOAT(Radius)
    IMPL_ATTRIBUTE_FLOAT(SelfCollisionStrength)
	IMPL_ATTRIBUTE_FLOAT(StrengthS4m)
	IMPL_ATTRIBUTE_FLOAT(StrengthS2m)
	IMPL_ATTRIBUTE_BOOL(CanShow)
	IMPL_ATTRIBUTE_STRING(FixedPoints)
    IMPL_ATTRIBUTE_STRING(ExpandedPoints)
	IMPL_ATTRIBUTE_BOOL(CanCut)
	IMPL_ATTRIBUTE_FLOAT(TetraStiff)
	IMPL_ATTRIBUTE_FLOAT(TetraDamp)
	IMPL_ATTRIBUTE_FLOAT(TetraPointDamp)
	IMPL_ATTRIBUTE_FLOAT(ForceFeedbackRatio)
	IMPL_ATTRIBUTE_FLOAT(HomingForce)

	DECLARE_SERIALIZATION_CLASS(CXMLWrapperPart)
};

