/**Author:zx**/
#include "StdAfx.h"
#include "XMLWrapperParticle.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperParticle)
REGISTER_CLASS(Particle)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Name,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Type,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,InitialVelocity,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Radius,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Mass,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Life,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,Force,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,RandomForce,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,EmitRate,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,MaterialName,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,LiveTimeAfterStop,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,BillboardWidth,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperParticle,BillboardHeight,VALUE)
END_IMPL_SERIALIZATION_CLASS

CXMLWrapperParticle::CXMLWrapperParticle(void)
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_STRING(Type)
	INIT_ATTRIBUTE_FLOAT3(InitialVelocity)
	INIT_ATTRIBUTE_FLOAT(Radius)
	INIT_ATTRIBUTE_FLOAT(Mass)
	INIT_ATTRIBUTE_FLOAT(Life)
	INIT_ATTRIBUTE_FLOAT3(Force)
	INIT_ATTRIBUTE_FLOAT3(RandomForce)
	INIT_ATTRIBUTE_FLOAT(EmitRate)
	INIT_ATTRIBUTE_STRING(MaterialName)
	INIT_ATTRIBUTE_FLOAT(LiveTimeAfterStop)
	INIT_ATTRIBUTE_FLOAT(BillboardWidth)
	INIT_ATTRIBUTE_FLOAT(BillboardHeight)
}

CXMLWrapperParticle::~CXMLWrapperParticle(void)
{

}