#include "StdAfx.h"
#include "XMLWrapperPart.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperPart)
	REGISTER_CLASS(Part)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,Name,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,FileName,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,Type,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,Length,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,FirstPointPos,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,Orientation,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,Mass,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,EdgeStiff,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,BendStiff,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,TorsionStiff,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,EdgeDamp,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,ExtraEdgeDamp,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,BendDamp,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,TorsionDamp,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,Interval,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,Radius,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,SelfCollisionStrength,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,StrengthS4m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,StrengthS2m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,CanShow,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,FixedPoints,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperPart,ExpandedPoints,VALUE)    
	REGISTER_ATTRIBUTE(CXMLWrapperPart,CanCut,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,TetraStiff,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,TetraDamp,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,TetraPointDamp,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,ForceFeedbackRatio,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperPart,HomingForce,VALUE)
END_IMPL_SERIALIZATION_CLASS


CXMLWrapperPart::CXMLWrapperPart( void )
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_STRING(FileName)
	INIT_ATTRIBUTE_LONG(Type)
	INIT_ATTRIBUTE_FLOAT(Length)
	INIT_ATTRIBUTE_FLOAT3(FirstPointPos)
    INIT_ATTRIBUTE_LONG(Orientation)
    INIT_ATTRIBUTE_FLOAT(Mass)
    INIT_ATTRIBUTE_FLOAT(EdgeStiff)
    INIT_ATTRIBUTE_FLOAT(BendStiff)
    INIT_ATTRIBUTE_FLOAT(TorsionStiff)
    INIT_ATTRIBUTE_FLOAT(EdgeDamp)
    INIT_ATTRIBUTE_FLOAT(ExtraEdgeDamp)
    INIT_ATTRIBUTE_FLOAT(BendDamp)
    INIT_ATTRIBUTE_FLOAT(TorsionDamp)
    INIT_ATTRIBUTE_FLOAT(Interval)
    INIT_ATTRIBUTE_FLOAT(Radius)
    INIT_ATTRIBUTE_FLOAT(SelfCollisionStrength)
	INIT_ATTRIBUTE_FLOAT(StrengthS4m)
	INIT_ATTRIBUTE_FLOAT(StrengthS2m)
	INIT_ATTRIBUTE_STRING(FixedPoints)
    INIT_ATTRIBUTE_STRING(ExpandedPoints)    
	INIT_ATTRIBUTE_FLOAT(TetraStiff)
	INIT_ATTRIBUTE_FLOAT(TetraDamp)
	INIT_ATTRIBUTE_FLOAT(ForceFeedbackRatio)
	INIT_ATTRIBUTE_FLOAT_VALUE(ForceFeedbackRatio, 1.0f)
	INIT_ATTRIBUTE_FLOAT(HomingForce)

	m_TetraPointDamp = 0.99;
	m_CanCut = true;
	m_CanShow = true;
}

CXMLWrapperPart::~CXMLWrapperPart( void )
{

}
