#include "StdAfx.h"
#include "XMLWrapperScore.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperScore)
REGISTER_CLASS(Score)
REGISTER_ATTRIBUTE(CXMLWrapperScore,Name,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,Description,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,Score,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,TimeScore,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,TimeLimit,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,ExtendTimeScore,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,ExtendTimeLimit,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,Condition,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,CustomPosX,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,CustomPosY,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,ValidTimes,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,LastSeconds,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperScore,ValidTimeInterval,VALUE)
END_IMPL_SERIALIZATION_CLASS

CXMLWrapperScore::CXMLWrapperScore(void)
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_STRING(Description)
	INIT_ATTRIBUTE_FLOAT(Score)
	INIT_ATTRIBUTE_FLOAT(TimeScore)
	INIT_ATTRIBUTE_FLOAT(TimeLimit)
	INIT_ATTRIBUTE_FLOAT(ExtendTimeScore)
	INIT_ATTRIBUTE_FLOAT(ExtendTimeLimit)
	INIT_ATTRIBUTE_STRING(Condition)
	INIT_ATTRIBUTE_LONG(CustomPosX)
	INIT_ATTRIBUTE_LONG(CustomPosY)
	INIT_ATTRIBUTE_LONG(ValidTimes)

	INIT_ATTRIBUTE_LONG(LastSeconds)
	INIT_ATTRIBUTE_FLOAT_VALUE(ValidTimeInterval,1.f);
	m_LastSeconds=5;
}

CXMLWrapperScore::~CXMLWrapperScore(void)
{
}
