/**Author:zx**/
#include "StdAfx.h"
#include "XMLWrapperTool.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperTool)
	REGISTER_CLASS(Tool)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Name,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Type,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,SubType,VALUE)
	//REGISTER_ATTRIBUTE(CXMLWrapperTool,Mesh,ARRAY)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Path,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Root,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Left,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Right,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Left_a1,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Right_b1,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Left_a2,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Right_b2,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Center,VALUE)

	// physics
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Lefts4m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Rights4m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Kernels4m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Lefts2m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Rights2m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,OuterLefts2m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,OuterRights2m,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Kernels2m,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,NeedTriangleDetection,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,Mass,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Stiffness,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Damp,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,PointDamp,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Strength,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,Thickness,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,HeadLength,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,PointResistence,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CollisionRadius,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,S4mShift,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,TriangleShift,VALUE)

	//Usage
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanPuncture,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanCut,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanClamp,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanRelease,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanFire,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanDistance,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanSeparate,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanClosed,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ExcuHeldPoints,VALUE)

	//通电优先级
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ElecPriority,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,IsIgnoreElecPriority,VALUE)

	

	//Clip Applier
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ClipApplierHeadHalfWidth,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ClipApplierHeadLength,VALUE)

	//Scissors
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolUpRelaxAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolDownRelaxAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolUpTightAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolDownTightAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolHeadAngle,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolUpLength,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,ToolDownLength,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanBlood,VALUE)
    REGISTER_ATTRIBUTE(CXMLWrapperTool,CanStopBlood,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanDrawS2M,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanDrawS4M,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanDrawTriangle,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,ElectricTime,VALUE);

	REGISTER_ATTRIBUTE(CXMLWrapperTool,HookPosition,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,CanAdhesionForce,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,CutNumber,VALUE)

	REGISTER_ATTRIBUTE(CXMLWrapperTool,MaxShaftAside,VALUE)

END_IMPL_SERIALIZATION_CLASS

CXMLWrapperTool::CXMLWrapperTool(void)
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_STRING(Type)
	INIT_ATTRIBUTE_STRING(SubType)
	INIT_ATTRIBUTE_STRING(Path)
	INIT_ATTRIBUTE_STRING(Root)
	INIT_ATTRIBUTE_STRING(Left)
	INIT_ATTRIBUTE_STRING(Right)

	//physics
	INIT_ATTRIBUTE_STRING(Lefts4m)
	INIT_ATTRIBUTE_STRING(Rights4m)
	INIT_ATTRIBUTE_STRING(Kernels4m)
	INIT_ATTRIBUTE_STRING(Lefts2m)
	INIT_ATTRIBUTE_STRING(Rights2m)
	INIT_ATTRIBUTE_STRING(OuterLefts2m)
	INIT_ATTRIBUTE_STRING(OuterRights2m)
	INIT_ATTRIBUTE_STRING(Kernels2m)
	INIT_ATTRIBUTE_FLOAT(Mass)
	INIT_ATTRIBUTE_FLOAT(Stiffness)
	INIT_ATTRIBUTE_FLOAT(Damp)
	INIT_ATTRIBUTE_FLOAT(PointDamp)
	INIT_ATTRIBUTE_FLOAT(Strength)
	INIT_ATTRIBUTE_FLOAT(Thickness)
	INIT_ATTRIBUTE_FLOAT(HeadLength)
	INIT_ATTRIBUTE_FLOAT(PointResistence)
	INIT_ATTRIBUTE_FLOAT(CollisionRadius)

	INIT_ATTRIBUTE_BOOL(NeedTriangleDetection)

	INIT_ATTRIBUTE_FLOAT3(S4mShift)
	INIT_ATTRIBUTE_FLOAT3(TriangleShift)

	// usage
	INIT_ATTRIBUTE_BOOL(CanPuncture)
	INIT_ATTRIBUTE_BOOL(CanCut)
	INIT_ATTRIBUTE_BOOL(CanClamp)
	INIT_ATTRIBUTE_BOOL(CanRelease)
	INIT_ATTRIBUTE_BOOL(CanFire)
	INIT_ATTRIBUTE_BOOL(CanDistance)
	INIT_ATTRIBUTE_BOOL(CanSeparate)
	INIT_ATTRIBUTE_BOOL(ExcuHeldPoints)
	INIT_ATTRIBUTE_BOOL(CanClosed)
	INIT_ATTRIBUTE_BOOL_VALUE(ExcuHeldPoints, true)

	INIT_ATTRIBUTE_LONG_VALUE(ElecPriority, 0)
	INIT_ATTRIBUTE_BOOL_VALUE(IsIgnoreElecPriority, false)


	// Clip Applier
	INIT_ATTRIBUTE_FLOAT(ClipApplierHeadHalfWidth)
	INIT_ATTRIBUTE_FLOAT(ClipApplierHeadLength)

	//Scissors
	INIT_ATTRIBUTE_FLOAT(ToolUpRelaxAngle)
	INIT_ATTRIBUTE_FLOAT(ToolDownRelaxAngle)
	INIT_ATTRIBUTE_FLOAT(ToolUpTightAngle)
	INIT_ATTRIBUTE_FLOAT(ToolDownTightAngle)
	INIT_ATTRIBUTE_FLOAT(ToolHeadAngle)
	INIT_ATTRIBUTE_FLOAT(ToolUpLength)
	INIT_ATTRIBUTE_FLOAT(ToolDownLength)

	INIT_ATTRIBUTE_FLOAT(ElectricTime)

	INIT_ATTRIBUTE_BOOL(CanBlood)
	INIT_ATTRIBUTE_BOOL(CanStopBlood)

	INIT_ATTRIBUTE_BOOL(CanDrawS2M)
	INIT_ATTRIBUTE_BOOL(CanDrawS4M)
	INIT_ATTRIBUTE_BOOL(CanDrawTriangle)

	INIT_ATTRIBUTE_FLOAT3(HookPosition)

	INIT_ATTRIBUTE_BOOL(CanAdhesionForce)

	INIT_ATTRIBUTE_LONG_VALUE(CutNumber,1)

	INIT_ATTRIBUTE_FLOAT_VALUE(MaxShaftAside,60)
}


CXMLWrapperTool::~CXMLWrapperTool(void)
{
}

//void __stdcall CXMLWrapperTool::Set_Mesh(Variant value)
//{
//	if (value.vt != SYVT_I4 && value.lVal != 0)
//	{
//		return;	
//	}
//	
//	m_Mesh.push_back((CXMLWrapperMeshNode *)value.lVal);
//	m_flag_Mesh = true;
//}
//
//void __stdcall CXMLWrapperTool::Get_Mesh(Variant * pValue)
//{
//
//}