#include "StdAfx.h"
#include "XMLWrapperOperateItem.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperOperateItem)
REGISTER_CLASS(OperateItem)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,Name,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,Description,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,ID,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,Category,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,Score,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,TimeScore,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,TimeLimit1,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,TimeLimit2,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,FalloffFactor,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,ValidTimes,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,MinScoreInterval,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,Value,VALUE)
REGISTER_ATTRIBUTE(CXMLWrapperOperateItem,ValueType,VALUE)
END_IMPL_SERIALIZATION_CLASS

CXMLWrapperOperateItem::CXMLWrapperOperateItem(void)
{
	INIT_ATTRIBUTE_STRING(Name)
	INIT_ATTRIBUTE_STRING(Description)
	INIT_ATTRIBUTE_LONG_VALUE(ID,1000000)
	INIT_ATTRIBUTE_LONG_VALUE(Category,0)
	INIT_ATTRIBUTE_FLOAT_VALUE(Score,0)
	INIT_ATTRIBUTE_FLOAT_VALUE(TimeScore,0)
	INIT_ATTRIBUTE_FLOAT_VALUE(TimeLimit1,10000000)
	INIT_ATTRIBUTE_FLOAT_VALUE(TimeLimit2,10000000)
	INIT_ATTRIBUTE_FLOAT_VALUE(FalloffFactor,1)
	INIT_ATTRIBUTE_LONG_VALUE(ValidTimes,10000000)
	INIT_ATTRIBUTE_FLOAT_VALUE(MinScoreInterval,0)
	INIT_ATTRIBUTE_FLOAT_VALUE(Value,0)
	INIT_ATTRIBUTE_STRING_VALUE(ValueType,"Number")
}

CXMLWrapperOperateItem::~CXMLWrapperOperateItem(void)
{
}
