#include "StdAfx.h"
#include "XMLWrapperAdhere.h"

BEGIN_IMPL_SERIALIZATION_CLASS(CXMLWrapperAdhere)
	REGISTER_CLASS(AdhereEntity)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,Object1ID,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,Object2ID,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,Range,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,Ratio,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere, MergedObjectIDS, VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,AdhereType,VALUE)
	REGISTER_ATTRIBUTE(CXMLWrapperAdhere,HideLinkFace,VALUE)

END_IMPL_SERIALIZATION_CLASS


CXMLWrapperAdhere::CXMLWrapperAdhere( void )
{
	INIT_ATTRIBUTE_LONG(Object1ID)
	INIT_ATTRIBUTE_LONG(Object2ID)
	INIT_ATTRIBUTE_FLOAT_VALUE(Range,0.05)
	//INIT_ATTRIBUTE_FLOAT(Ratio)
	INIT_ATTRIBUTE_FLOAT_VALUE(Ratio, 0)
	INIT_ATTRIBUTE_STRING(MergedObjectIDS)
	INIT_ATTRIBUTE_STRING_VALUE(AdhereType , "Approach")
	INIT_ATTRIBUTE_BOOL_VALUE(HideLinkFace , true)
}

CXMLWrapperAdhere::~CXMLWrapperAdhere( void )
{

}